version: "3.8"

services:
  spring-boot:  
    image: openjdk:17-jdk
    container_name: spring-boot
    volumes:
      - ./java-spring-boot:/app
    working_dir: /app
    command: "./mvnw spring-boot:run -Dspring-boot.run.profiles=dev"
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: Asia/Shanghai
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  flask:
    build: ./python-flask
    container_name: flask
    environment:
      - TZ=Asia/Shanghai
      - CORS_ALLOWED_ORIGINS=*
      - JAVA_SERVICE_URL=http://spring-boot:8080
      - VUE_SERVICE_URL=http://vue:3000
    ports:
      - "5001:5001"
    volumes:
      - ./python-flask:/app
      - ./data:/app/data

  vue:
    build: ./vue
    container_name: vue
    ports:
      - "3000:3000"
    working_dir: /app
    environment:
      - JAVA_SERVICE_URL=http://spring-boot:8080
      - FLASK_SERVICE_URL=http://flask:5001
      - TZ=Asia/Shanghai
    volumes:
      - ./vue:/app
      - /app/node_modules