version: '3.8'
services:
  vue:
    image: node:lts
    container_name: vue-container
    ports:
      - '3000:3000'
    volumes:
      - ./src/main:/app
    working_dir: /app
    environment:
      TZ: Asia/Shanghai